<?php
session_start();
if (!isset($_SESSION['user_id'])) { header("Location: index.php"); exit(); }

require_once('db.php');
$my_uid = $_SESSION['user_id'];

// Clear real-time alerts safely
$conn->query("UPDATE Notifications SET is_read=1 WHERE user_id='$my_uid'");

if (isset($_POST['action_resolution'])) {
    $req_id = $conn->real_escape_string($_POST['request_id']);
    $resolution = $conn->real_escape_string($_POST['status_value']);
    
    if ($conn->query("UPDATE Project_Requests SET status='$resolution' WHERE request_id='$req_id' AND receiver_id='$my_uid'")) {
        $target_req = $conn->query("SELECT sender_id, project_title FROM Project_Requests WHERE request_id='$req_id'")->fetch_assoc();
        $sender_target = $target_req['sender_id'];
        $notif_text = $conn->real_escape_string($_SESSION['fullname'] . " has " . strtolower($resolution) . " your proposal: " . $target_req['project_title']);
        $conn->query("INSERT INTO Notifications (user_id, message) VALUES ('$sender_target', '$notif_text')");
    }
}

$incoming_proposals = $conn->query("SELECT Project_Requests.*, Users.fullname, Users.headline, Users.whatsapp_num 
                                    FROM Project_Requests JOIN Users ON Project_Requests.sender_id = Users.user_id 
                                    WHERE receiver_id='$my_uid' ORDER BY Project_Requests.created_at DESC");
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SkillSwap | Proposals Desk</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body class="bg-slate-900 text-slate-100 min-h-screen flex">

    <?php include('includes/sidebar.php'); ?>

    <main class="flex-1 p-6 md:p-10 max-h-screen overflow-y-auto">
        <header class="mb-8">
            <h1 class="text-xl font-bold text-white">Direct Project Proposals Workspace 💼</h1>
            <p class="text-slate-400 text-xs mt-1">Review live structural requests generated by client nodes across the app network.</p>
        </header>

        <div class="space-y-4 max-w-3xl">
            <?php if ($incoming_proposals->num_rows == 0): ?>
                <div class="bg-slate-950 p-8 rounded-2xl border border-slate-800 text-center text-slate-500 text-xs">No active contracts received.</div>
            <?php else: ?>
                <?php while($req = $incoming_proposals->fetch_assoc()): ?>
                <div class="bg-slate-950 p-5 rounded-2xl border border-slate-800 space-y-3 shadow-lg">
                    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 pb-3 border-b border-slate-900">
                        <div>
                            <h3 class="text-xs font-bold text-white text-indigo-400 font-mono">[<?= $req['status'] ?>] - <?= $req['project_title'] ?></h3>
                            <p class="text-[10px] text-slate-500 mt-0.5">From: <b><?= $req['fullname'] ?></b> (<?= $req['headline'] ?>)</p>
                        </div>
                        <span class="text-[10px] text-slate-600"><?= date('M d, Y', strtotime($req['created_at'])) ?></span>
                    </div>
                    
                    <p class="text-slate-300 text-xs leading-relaxed bg-slate-900/50 p-3 rounded-xl border border-slate-900"><?= nl2br($req['proposal_details']) ?></p>

                    <div class="flex justify-between items-center pt-1">
                        <a href="https://wa.me/<?= $req['whatsapp_num'] ?>" target="_blank" class="text-[11px] text-emerald-400 hover:underline"><i class="fa-brands fa-whatsapp mr-1"></i> Sync via WhatsApp</a>
                        
                        <?php if($req['status'] == 'Pending'): ?>
                        <form action="" method="POST" class="flex gap-2">
                            <input type="hidden" name="request_id" value="<?= $req['request_id'] ?>">
                            <button type="submit" name="action_resolution" value="1" onclick="this.form.appendChild(Object.assign(document.createElement('input'),{type:'hidden',name:'status_value',value:'Accepted'}))" class="bg-emerald-600 hover:bg-emerald-500 text-white text-[10px] px-3 py-1.5 rounded-lg transition font-semibold">Accept</button>
                            <button type="submit" name="action_resolution" value="1" onclick="this.form.appendChild(Object.assign(document.createElement('input'),{type:'hidden',name:'status_value',value:'Declined'}))" class="bg-slate-800 hover:bg-rose-600 text-slate-400 hover:text-white text-[10px] px-3 py-1.5 rounded-lg transition border border-slate-700">Decline</button>
                        </form>
                        <?php else: ?>
                            <span class="text-[10px] font-bold uppercase px-2.5 py-1 rounded-md <?= $req['status']=='Accepted' ? 'bg-emerald-500/10 text-emerald-400' : 'bg-rose-500/10 text-rose-400' ?>"><?= $req['status'] ?></span>
                        <?php endif; ?>
                    </div>
                </div>
                <?php endwhile; ?>
            <?php endif; ?>
        </div>
    </main>

</body>
</html>